name: SpecFlowProject11

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8'  # Replace with the desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet vstest C:\Users\HAJABDALLAHOussama\Desktop\Myproject\SpecFlowProject11\SpecFlowProject11\bin\Debug\net48\SpecFlowProject11.dll
